name: piper-test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# set environment variables for all jobs
env:
  ARTIFACTPREPAREVERSION_FLAGS: '["--shortCommitId", "--buildTool", "maven", "--verbose"]'
  MAVENBUILD_FLAGS: '["--verify", "--verbose", "--logSuccessfulMavenTransfers"]'
  GRADLEEXECUTEBUILD_FLAGS: '["--verbose"]'

permissions:
  contents: write

jobs:
  piper-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: gradleExecuteBuild
        # use fork from https://github.com/hilmarf/project-piper-action/tree/pass/stepFlagsEnvVar
        uses: hilmarf/project-piper-action@pass/stepFlagsEnvVar
        with:
          step-name: gradleExecuteBuild
          docker-image: "gradle:9.1-jdk25"

      - name: mavenBuild
        # use fork from https://github.com/hilmarf/project-piper-action/tree/pass/stepFlagsEnvVar
        uses: hilmarf/project-piper-action@pass/stepFlagsEnvVar
        with:
          step-name: mavenBuild
